"""
Phase 24 Thread 2 — Bilateral Triple Module Action
Chavez AI Labs LLC · March 25, 2026

Phase 21C showed H5 module action is ill-defined for the full 6-root set.
Phase 23T1 found {q2, q3, q4} has a FINITE 12-vector closure.
This thread tests whether L_q3 (left multiplication by q3) maps the 12-vector
closure to itself, and whether [H5, L_q3]=0 constrains H5 eigenvalues.

Key question: Does the finite bilateral triple algebra open a new algebraic
path to constraining H5, or does it close this avenue definitively?
"""

import numpy as np
import json
import math
from itertools import product as iproduct

# ── Sedenion multiplication ──────────────────────────────────────────────────

def cd_conj(v):
    return [v[0]] + [-x for x in v[1:]]

def cd_mul(a, b):
    n = len(a)
    if n == 1:
        return [a[0] * b[0]]
    h = n // 2
    a1, a2, b1, b2 = a[:h], a[h:], b[:h], b[h:]
    c1 = [x - y for x, y in zip(cd_mul(a1, b1), cd_mul(cd_conj(b2), a2))]
    c2 = [x + y for x, y in zip(cd_mul(b2, a1), cd_mul(a2, cd_conj(b1)))]
    return c1 + c2

def sed_mul(a, b):
    """Multiply two 16D sedenion vectors (lists or arrays)."""
    return cd_mul(list(a), list(b))

# ── 12-vector closure of {q2, q3, q4} — Phase 23T1 ─────────────────────────

sqrt2 = math.sqrt(2.0)

def make_16d(positions_values):
    """Create a 16D sedenion vector from {position: value} dict."""
    v = [0.0] * 16
    for pos, val in positions_values.items():
        v[pos] = val
    return v

# Basis vectors (unnormalized for sedenion multiplication; norm^2=2 for q2,q3,q4)
# Phase 23T1 used unnormalized roots. 12-vector closure is normalized to norm=1.
# We use norm-1 vectors for the module action analysis.

inv_sqrt2 = 1.0 / sqrt2

CLOSURE_VECS_16D = {
    's':        make_16d({0: -1.0}),                              # scalar -e0
    'neg_q4':   make_16d({3: -inv_sqrt2, 12: -inv_sqrt2}),       # -q4
    'neg_q2':   make_16d({5: -inv_sqrt2, 10: +inv_sqrt2}),       # sign partner of q2
    'sp_q3_neg':make_16d({6: -inv_sqrt2,  9: +inv_sqrt2}),       # sign partner of q3 (-)
    'neg_e15':  make_16d({15: -1.0}),                            # -e15
    'pos_e15':  make_16d({15: +1.0}),                            # +e15
    'sp_q3_pos':make_16d({6: +inv_sqrt2,  9: -inv_sqrt2}),       # sign partner of q3 (+)
    'q3':       make_16d({6: +inv_sqrt2,  9: +inv_sqrt2}),       # q3 (bilateral hub)
    'sp_q2':    make_16d({5: +inv_sqrt2, 10: -inv_sqrt2}),       # sign partner of q2
    'q2':       make_16d({5: +inv_sqrt2, 10: +inv_sqrt2}),       # q2
    'q4':       make_16d({3: +inv_sqrt2, 12: -inv_sqrt2}),       # q4
    'new_dir':  make_16d({3: +inv_sqrt2, 12: +inv_sqrt2}),       # (e3+e12)/sqrt2
}

CLOSURE_LABELS = list(CLOSURE_VECS_16D.keys())
CLOSURE_VECS   = [CLOSURE_VECS_16D[k] for k in CLOSURE_LABELS]
N_CLOSURE = len(CLOSURE_VECS)

def norm2(v):
    return sum(x*x for x in v)

def dot16(a, b):
    return sum(x*y for x, y in zip(a, b))

def vec_norm(v):
    return math.sqrt(norm2(v))

# Verify norms
print("=== Verifying 12-vector closure norms ===")
for label, vec in zip(CLOSURE_LABELS, CLOSURE_VECS):
    n2 = norm2(vec)
    print(f"  {label:15s}: norm^2 = {n2:.6f}")

# q3 unnormalized (for the left-multiplication generating element)
# The handoff says q3 = e6 + e9 (unnormalized, norm^2 = 2).
# For the action, we should use the unnormalized q3 since the closure was generated by it.
# BUT the closure vectors themselves are normalized (norm=1).
# Using normalized q3 for L_q3 action:
Q3_NORM = CLOSURE_VECS_16D['q3']   # normalized, norm=1

# For physical sedenion action (preserving algebra), also test with unnormalized:
Q3_UNNORM = make_16d({6: 1.0, 9: 1.0})   # norm^2 = 2

def is_zero_vec(v, tol=1e-8):
    return max(abs(x) for x in v) < tol

def find_in_closure(v, tol=1e-8):
    """Check if v is in span of closure vectors; return (label, sign, exact_match)."""
    if is_zero_vec(v, tol):
        return None, None, True, "zero"
    n = vec_norm(v)
    if n < tol:
        return None, None, True, "zero"
    v_dir = [x / n for x in v]
    for i, (label, cv) in enumerate(zip(CLOSURE_LABELS, CLOSURE_VECS)):
        c_norm = vec_norm(cv)
        if c_norm < tol:
            continue
        cv_dir = [x / c_norm for x in cv]
        dot = sum(a*b for a, b in zip(v_dir, cv_dir))
        if abs(dot - 1.0) < tol:
            return i, +1, True, f"+{label} (scale={n:.4f})"
        if abs(dot + 1.0) < tol:
            return i, -1, True, f"-{label} (scale={n:.4f})"
    # Not a multiple of a closure vector; check if it's a sum
    return None, None, False, "ESCAPE"

def safe(x):
    if x is None:
        return None
    if isinstance(x, (list, tuple)):
        return [safe(i) for i in x]
    if isinstance(x, np.ndarray):
        return x.tolist()
    if isinstance(x, (np.bool_,)):
        return bool(x)
    if isinstance(x, (np.integer,)):
        return int(x)
    if isinstance(x, (np.floating,)):
        if math.isnan(x) or math.isinf(x):
            return None
        return float(x)
    if isinstance(x, float):
        if math.isnan(x) or math.isinf(x):
            return None
    return x

# ── Section 1: Full 12x12 multiplication table ───────────────────────────────

print("\n=== Section 1: Full 12x12 multiplication table ===")

mul_table = {}  # (i, j) -> (label_result, is_zero, in_closure, scale)
n_zero = 0
n_in_closure = 0
n_escape = 0

for i, (li, vi) in enumerate(zip(CLOSURE_LABELS, CLOSURE_VECS)):
    for j, (lj, vj) in enumerate(zip(CLOSURE_LABELS, CLOSURE_VECS)):
        prod = sed_mul(vi, vj)
        if is_zero_vec(prod):
            n_zero += 1
            mul_table[(i, j)] = {'is_zero': True, 'in_closure': True, 'result_label': 'zero', 'scale': 0.0}
        else:
            idx, sign, exact, desc = find_in_closure(prod)
            if exact and idx is not None:
                n_in_closure += 1
                mul_table[(i, j)] = {
                    'is_zero': False, 'in_closure': True,
                    'result_label': CLOSURE_LABELS[idx],
                    'result_sign': sign,
                    'scale': vec_norm(prod),
                    'desc': desc
                }
            elif exact and idx is None:
                # This shouldn't happen (would be zero caught above)
                mul_table[(i, j)] = {'is_zero': True, 'in_closure': True, 'result_label': 'zero', 'scale': 0.0}
            else:
                n_escape += 1
                mul_table[(i, j)] = {
                    'is_zero': False, 'in_closure': False,
                    'result_vec': [round(x, 8) for x in prod],
                    'result_norm': vec_norm(prod),
                    'desc': 'ESCAPE'
                }

print(f"Total products: {N_CLOSURE * N_CLOSURE}")
print(f"  Zero products: {n_zero}")
print(f"  Non-zero, in closure: {n_in_closure}")
print(f"  Escapes closure: {n_escape}")
print(f"\nClosure is {'CLOSED' if n_escape == 0 else 'NOT CLOSED'} under sedenion multiplication.")

if n_escape > 0:
    print("\nEscape products (vi * vj):")
    for (i, j), info in mul_table.items():
        if not info.get('in_closure', True):
            print(f"  {CLOSURE_LABELS[i]:15s} * {CLOSURE_LABELS[j]:15s} -> ESCAPE norm={info['result_norm']:.4f}")
            # Show nonzero positions
            v = info['result_vec']
            nonzero = [(k, v[k]) for k in range(16) if abs(v[k]) > 1e-8]
            print(f"    Nonzero: {nonzero}")

# ── Section 2: L_q3 action on the closure ───────────────────────────────────

print("\n=== Section 2: L_q3 action on 12-vector closure ===")
print("(Left multiplication by normalized q3)")

L_q3_action = {}  # label -> (result_label, scale, is_zero, in_closure)
kernel_L_q3 = []  # vectors where q3 * v = 0
image_L_q3 = []   # nonzero results (as indices)

print(f"\n{'v':>15s}  q3 * v  {'In closure?':>12s}  Result")
print("-" * 70)

for i, (label, vec) in enumerate(zip(CLOSURE_LABELS, CLOSURE_VECS)):
    prod = sed_mul(Q3_NORM, vec)
    if is_zero_vec(prod):
        L_q3_action[label] = {'is_zero': True, 'in_closure': True, 'result': 'zero'}
        kernel_L_q3.append(label)
        print(f"{label:>15s}  q3*v  {'yes (zero)':>12s}  0")
    else:
        idx, sign, exact, desc = find_in_closure(prod)
        if exact and idx is not None:
            result_label = CLOSURE_LABELS[idx]
            scale = vec_norm(prod)
            sign_str = '+' if sign > 0 else '-'
            L_q3_action[label] = {
                'is_zero': False, 'in_closure': True,
                'result_label': result_label, 'result_sign': sign, 'scale': scale,
                'desc': desc
            }
            image_L_q3.append(idx)
            print(f"{label:>15s}  q3*v  {'yes':>12s}  {sign_str}{result_label} (scale={scale:.4f})")
        else:
            L_q3_action[label] = {'is_zero': False, 'in_closure': False, 'result': 'ESCAPE',
                                  'result_vec': prod}
            print(f"{label:>15s}  q3*v  {'ESCAPE':>12s}  {[round(x,4) for x in prod if abs(x)>1e-8]}")

print(f"\nKernel of L_q3 (q3*v = 0): {kernel_L_q3}")
print(f"Kernel size: {len(kernel_L_q3)}")
image_labels = list(dict.fromkeys(CLOSURE_LABELS[i] for i in image_L_q3))
print(f"Image of L_q3: {image_labels}")
print(f"Image size: {len(image_labels)}")

# ── Section 3: R_q3 action (right multiplication) ───────────────────────────

print("\n=== Section 3: R_q3 action on 12-vector closure ===")
print("(Right multiplication: v * q3)")

R_q3_action = {}
kernel_R_q3 = []

print(f"\n{'v':>15s}  v*q3  {'In closure?':>12s}  Result")
print("-" * 70)

for i, (label, vec) in enumerate(zip(CLOSURE_LABELS, CLOSURE_VECS)):
    prod = sed_mul(vec, Q3_NORM)
    if is_zero_vec(prod):
        R_q3_action[label] = {'is_zero': True, 'in_closure': True, 'result': 'zero'}
        kernel_R_q3.append(label)
        print(f"{label:>15s}  v*q3  {'yes (zero)':>12s}  0")
    else:
        idx, sign, exact, desc = find_in_closure(prod)
        if exact and idx is not None:
            result_label = CLOSURE_LABELS[idx]
            scale = vec_norm(prod)
            sign_str = '+' if sign > 0 else '-'
            R_q3_action[label] = {
                'is_zero': False, 'in_closure': True,
                'result_label': result_label, 'result_sign': sign, 'scale': scale
            }
            print(f"{label:>15s}  v*q3  {'yes':>12s}  {sign_str}{result_label} (scale={scale:.4f})")
        else:
            R_q3_action[label] = {'is_zero': False, 'in_closure': False, 'result': 'ESCAPE',
                                  'result_vec': prod}
            print(f"{label:>15s}  v*q3  {'ESCAPE':>12s}  ESCAPE")

print(f"\nKernel of R_q3 (v*q3 = 0): {kernel_R_q3}")
print(f"L_q3 kernel == R_q3 kernel: {set(kernel_L_q3) == set(kernel_R_q3)}")

# ── Section 4: Gram matrix of the 12-vector closure ─────────────────────────

print("\n=== Section 4: Gram matrix of 12-vector closure ===")

G12 = np.zeros((N_CLOSURE, N_CLOSURE))
for i, vi in enumerate(CLOSURE_VECS):
    for j, vj in enumerate(CLOSURE_VECS):
        G12[i, j] = dot16(vi, vj)

# Eigenvalues
eigvals_G12 = np.linalg.eigvalsh(G12)
print(f"G12 eigenvalues: {[round(x, 6) for x in eigvals_G12]}")
print(f"Rank of G12: {np.linalg.matrix_rank(G12)}")
print(f"Condition number: {eigvals_G12[-1] / max(abs(eigvals_G12[0]), 1e-14):.4f}")

# Compare with Phase 21A: G6 had eigenvalues {0, 1, 1, 1, 1, 2}
print(f"\nPhase 21A G6 eigenvalues: [0, 1, 1, 1, 1, 2]")
print(f"G12 unique eigenvalues: {sorted(set(round(x, 4) for x in eigvals_G12))}")

# ── Section 5: L_q3 as 12x12 matrix ────────────────────────────────────────

print("\n=== Section 5: L_q3 as 12x12 linear map ===")

# Represent the L_q3 action as a matrix in the closure basis.
# Since some products might escape (checked above), only build if closure is closed.
if n_escape > 0:
    print("WARNING: closure is not closed under multiplication — L_q3 matrix is approximate")

L_q3_matrix = np.zeros((N_CLOSURE, N_CLOSURE))
for j, (label, vec) in enumerate(zip(CLOSURE_LABELS, CLOSURE_VECS)):
    prod = sed_mul(Q3_NORM, vec)
    # Express prod in the closure basis (project onto each basis vector)
    for i, ci in enumerate(CLOSURE_VECS):
        L_q3_matrix[i, j] = dot16(prod, ci)

print(f"L_q3 matrix (in closure basis):")
# Print as a table (condensed)
print("Non-zero entries:")
for i in range(N_CLOSURE):
    for j in range(N_CLOSURE):
        if abs(L_q3_matrix[i, j]) > 1e-8:
            print(f"  ({CLOSURE_LABELS[i]:15s}, {CLOSURE_LABELS[j]:15s}): {L_q3_matrix[i, j]:.6f}")

# Eigenvalues of L_q3 matrix
eigvals_Lq3 = np.linalg.eigvals(L_q3_matrix)
print(f"\nL_q3 matrix eigenvalues: {[round(x.real, 4) for x in eigvals_Lq3]}")
print(f"L_q3 rank: {np.linalg.matrix_rank(L_q3_matrix)}")
print(f"L_q3 kernel dim: {N_CLOSURE - np.linalg.matrix_rank(L_q3_matrix)}")

# ── Section 6: Commutator [H5, L_q3] = 0 constraint ─────────────────────────

print("\n=== Section 6: Commutator [H5, L_q3] = 0 constraint ===")

# The centralizer of L_q3 in End(R^12): all matrices M with M*L_q3 = L_q3*M.
# Dimension of centralizer = sum of dim(Hom(V_i, V_j)) where V_i are eigenspaces of L_q3.
# For a diagonalizable L_q3 with distinct eigenvalues: centralizer = diagonal matrices.
# With repeated eigenvalues: centralizer is block-diagonal.

# Count multiplicity of each eigenvalue
from collections import Counter
eigval_rounded = [round(x.real, 4) for x in eigvals_Lq3]
eigval_counts = Counter(eigval_rounded)
print(f"L_q3 eigenvalue multiplicities: {dict(eigval_counts)}")

# Centralizer dimension = sum of m_i^2 where m_i are multiplicities
centralizer_dim = sum(m*m for m in eigval_counts.values())
print(f"Centralizer dimension of L_q3 in End(R^12): {centralizer_dim}")
print(f"Full matrix algebra End(R^12) dimension: {N_CLOSURE}^2 = {N_CLOSURE**2}")
print(f"Constraint from [H5, L_q3]=0: reduces from {N_CLOSURE**2} -> {centralizer_dim} free params")

# Symmetric matrices in centralizer (since H5 must be self-adjoint):
# Symmetric centralizer has dimension sum of m_i*(m_i+1)/2
sym_centralizer_dim = sum(m*(m+1)//2 for m in eigval_counts.values())
print(f"Symmetric centralizer dimension: {sym_centralizer_dim}")

# Phase 21A comparison: full 6-root Gram G6 had 4D unconstrained eigenspace for H5
# That means the symmetric centralizer of G6 (for [H5,G6]=0) had large dimension
# The 12-vector L_q3 centralizer is a different and potentially smaller constraint
print(f"\nPhase 21A comparison:")
print(f"  G6 (6-root Gram): eigenvalues [0,1,1,1,1,2], 4D unconstrained eigenspace")
print(f"  L_q3 on 12-closure: sym centralizer dim = {sym_centralizer_dim}")
if sym_centralizer_dim < N_CLOSURE*(N_CLOSURE+1)//2:
    print(f"  [H5, L_q3]=0 DOES impose constraints ({N_CLOSURE*(N_CLOSURE+1)//2 - sym_centralizer_dim} params eliminated)")
else:
    print(f"  [H5, L_q3]=0 imposes NO constraints (centralizer = full symmetric algebra)")

# ── Section 7: Kernel sub-module check ──────────────────────────────────────

print("\n=== Section 7: Kernel sub-module analysis ===")
print(f"Kernel of L_q3: {kernel_L_q3}")

# Check if kernel is closed under the 12x12 multiplication
kernel_indices = [CLOSURE_LABELS.index(k) for k in kernel_L_q3]
print(f"Kernel indices: {kernel_indices}")

kernel_closed = True
kernel_violations = []
for i in kernel_indices:
    for j in range(N_CLOSURE):
        entry = mul_table.get((i, j), {})
        if not entry.get('in_closure', True):
            kernel_closed = False
            kernel_violations.append((CLOSURE_LABELS[i], CLOSURE_LABELS[j]))

print(f"Is kernel(L_q3) closed under full 12x12 multiplication? {kernel_closed}")
if kernel_violations:
    print(f"Violations: {kernel_violations}")

# Check kernel vs bilateral zero divisor subspace {q2, -q2, q4, -q4, sp_q2, ...}
bilateral_labels = ['q2', 'neg_q2', 'sp_q2', 'q4', 'neg_q4']
bilateral_in_kernel = [l for l in bilateral_labels if l in kernel_L_q3]
print(f"\nBilateral zero divisors in kernel: {bilateral_in_kernel}")
print(f"Scalar and e15 in kernel: {[l for l in ['s', 'neg_e15', 'pos_e15'] if l in kernel_L_q3]}")

# ── Compile results ──────────────────────────────────────────────────────────

print("\n=== Summary ===")
print(f"12-vector closure under sedenion mul: {'CLOSED' if n_escape == 0 else 'NOT CLOSED'}")
print(f"  Zero products: {n_zero}/144")
print(f"  In-closure non-zero: {n_in_closure}/144")
print(f"  Escape products: {n_escape}/144")
print(f"Kernel(L_q3): {kernel_L_q3} (size={len(kernel_L_q3)})")
print(f"Image(L_q3): {image_labels} (size={len(image_labels)})")
print(f"Rank-nullity check: rank({np.linalg.matrix_rank(L_q3_matrix)}) + null({len(kernel_L_q3)}) = {np.linalg.matrix_rank(L_q3_matrix) + len(kernel_L_q3)} (total={N_CLOSURE})")
print(f"Centralizer dim of L_q3 (symmetric): {sym_centralizer_dim}")
print(f"Full symmetric algebra dim: {N_CLOSURE*(N_CLOSURE+1)//2}")

results = {
    "phase": "24",
    "thread": 2,
    "title": "Bilateral Triple Module Action",
    "date": "2026-03-25",
    "researcher": "Paul Chavez, Chavez AI Labs",
    "closure_labels": CLOSURE_LABELS,
    "n_closure_vectors": N_CLOSURE,

    "multiplication_table_summary": {
        "total_products": N_CLOSURE * N_CLOSURE,
        "zero_products": n_zero,
        "in_closure_nonzero": n_in_closure,
        "escape_products": n_escape,
        "closure_is_closed": n_escape == 0
    },

    "L_q3_action": {
        "kernel": kernel_L_q3,
        "kernel_size": len(kernel_L_q3),
        "image": image_labels,
        "image_size": len(image_labels),
        "per_vector": {
            label: {k: (safe(v) if not isinstance(v, list) else [safe(x) for x in v])
                    for k, v in action.items() if k != 'result_vec'}
            for label, action in L_q3_action.items()
        }
    },

    "R_q3_action": {
        "kernel": kernel_R_q3,
        "kernel_size": len(kernel_R_q3),
        "L_kernel_eq_R_kernel": set(kernel_L_q3) == set(kernel_R_q3),
    },

    "gram_matrix_G12": {
        "eigenvalues": safe(eigvals_G12.tolist()),
        "rank": int(np.linalg.matrix_rank(G12)),
        "unique_eigenvalues": sorted(set(round(x, 4) for x in eigvals_G12.tolist())),
        "phase21a_G6_eigenvalues": [0, 1, 1, 1, 1, 2]
    },

    "L_q3_matrix": {
        "matrix": safe(L_q3_matrix.tolist()),
        "eigenvalues": safe([round(x.real, 6) for x in eigvals_Lq3]),
        "rank": int(np.linalg.matrix_rank(L_q3_matrix)),
        "kernel_dim": N_CLOSURE - int(np.linalg.matrix_rank(L_q3_matrix)),
        "eigenvalue_multiplicities": dict(eigval_counts)
    },

    "commutator_constraint": {
        "centralizer_dim": centralizer_dim,
        "sym_centralizer_dim": sym_centralizer_dim,
        "full_sym_algebra_dim": N_CLOSURE*(N_CLOSURE+1)//2,
        "params_constrained": N_CLOSURE*(N_CLOSURE+1)//2 - sym_centralizer_dim,
        "constraint_is_nontrivial": sym_centralizer_dim < N_CLOSURE*(N_CLOSURE+1)//2
    },

    "kernel_submodule": {
        "is_closed_under_full_multiplication": kernel_closed,
        "bilateral_in_kernel": bilateral_in_kernel,
    },

    "key_findings": {
        "closure_closed": n_escape == 0,
        "L_q3_kernel_size": len(kernel_L_q3),
        "L_q3_image_size": len(image_labels),
        "commutator_nontrivial": sym_centralizer_dim < N_CLOSURE*(N_CLOSURE+1)//2,
        "new_algebraic_path_opened": (n_escape == 0) and (sym_centralizer_dim < N_CLOSURE*(N_CLOSURE+1)//2)
    }
}

with open('phase24_thread2_results.json', 'w') as f:
    json.dump(results, f, indent=2)
print("\nResults saved to phase24_thread2_results.json")
print("\n=== PHASE 24 THREAD 2 COMPLETE ===")
